---
framework: mocha
preRun:
     command:
        - yarn

preMerge:
  pattern:
    - "node-tests/blueprints/**/*-test.js"

postMerge:
  pattern: 
    - "node-tests/blueprints/**/*-test.js"


version: 1.0