name: Alpha Releases

on:
  schedule:
    - cron:  '0 20 * * 3' # weekly (Wednesday)

jobs:
  test:
    name: Basic Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
        run: yarn ember build
      - name: test
        env:
          TEST_SUITE: each-package
        run: yarn test

  release:
    name: Tag + Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: setup git
        run: |
          git config --local user.email 'tomster@emberjs.com'
          git config --local user.name 'Ember.js Alpha Releaser'
      - name: Find next alpha
        run: |
          LATEST_ALPHA=`npm view ember-source dist-tags.alpha`
          export NEXT_ALPHA=`node bin/next-alpha-version.js ${LATEST_ALPHA}`
          echo "NEXT_ALPHA=$NEXT_ALPHA" >> $GITHUB_ENV
      - name: tag the next alpha
        run: npm version ${{env.NEXT_ALPHA}} --allow-same-version
      - name: build for publish
        env:
          BUILD_TYPE: alpha
          OVERRIDE_FEATURES: ''
        run: node bin/build-for-publishing.js
      - name: publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: push tag
        # Push in a way that will NOT trigger other workflows
        run: git push origin v${{env.NEXT_ALPHA}}
